# Site settings
title: A blog about astrophysics and statistics
description: A blog about astrophysics and statistics
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: |
  Valentina<br>
  Di Marco<br><br>
user_description: >
  Hi, I’m Valentina, an astrophysicist with a genuine love for statistics
  (yes, I truly love statistics, don’t hold it against me)!<br><
  
  I am currently a Research Fellow at the University of Melbourne, working with Andrew Melatos.<br><br>
  
  I recently completed a PhD in Astrophysics, with a thesis titled
  "Towards Rigorous Inference of Nanohertz Gravitational Waves",
  supervised by Erich Thrane, Ryan Shannon, and Andrew Zic.<br>
  
  Before that, I completed an MPhil in Statistics with a thesis titled
  "Novel Approach to the Reconstruction of Partially Detected Evolving Systems",
  under the supervision of Jonathan Keith and Distinguished Professor Kerrie Mengersen
  (available <a href="https://bridges.monash.edu/articles/thesis/Novel_Approach_to_the_Reconstruction_of_Partially_Detected_Evolving_Systems/19172537?file=34065434" target="_blank" rel="noopener">here</a>).<br>

  I also have over 18 years of experience in digital marketing.

user_title: |
  Astrophysicist<br><br>
  Statistician<br><br>
  Digital Marketing Consultant
twitter_username: valeaussie
github_username: valeaussie

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
